apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarath-groww
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: sarath-springboot
        image: 636352/growspringboot:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8085

#service type load-balancer

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
spec:
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8085
      targetport: 8085
  type: load-balancer
          
